INFO:root:s2a_fm version 1.2    Copyright(C) 2013-14 Alan Yorinks    All Rights Reserved 
INFO:root:com port = /dev/ttyATH0
ERROR:root:Could not instantiate PyMata - is your Arduino plugged in?
Traceback (most recent call last):
  File "C:\Users\AndrewLin\Desktop\PyFirmata\s2a_fm-master\s2a_fm-master\Snap!Files\Snap!Mobile\arduino\s2a_fm.py", line 70, in s2a_fm
    firmata = PyMata(com_port)  # pragma: no cover
  File "C:\Users\AndrewLin\Desktop\PyFirmata\s2a_fm-master\s2a_fm-master\Snap!Files\Snap!Mobile\arduino\PyMata\pymata.py", line 101, in __init__
    self._arduino = PyMataSerial(port_id, self._command_deque)
  File "C:\Users\AndrewLin\Desktop\PyFirmata\s2a_fm-master\s2a_fm-master\Snap!Files\Snap!Mobile\arduino\PyMata\pymata_serial.py", line 52, in __init__
    timeout=int(self.timeout))
  File "C:\Users\AndrewLin\Desktop\PyFirmata\s2a_fm-master\s2a_fm-master\Snap!Files\Snap!Mobile\arduino\serial\serialwin32.py", line 38, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Users\AndrewLin\Desktop\PyFirmata\s2a_fm-master\s2a_fm-master\Snap!Files\Snap!Mobile\arduino\serial\serialutil.py", line 282, in __init__
    self.open()
  File "C:\Users\AndrewLin\Desktop\PyFirmata\s2a_fm-master\s2a_fm-master\Snap!Files\Snap!Mobile\arduino\serial\serialwin32.py", line 66, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
SerialException: could not open port '/dev/ttyATH0': WindowsError(3, 'The system cannot find the path specified.')
DEBUG:root:Exiting s2a_fm
